// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MyDay",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "MyDay",
            targets: ["AppModule"],
            bundleIdentifier: "MyDay.water",
            teamIdentifier: "V3P2DS28T8",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .sun),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .faceID(purposeString: "使用FaceID来进入软件的隐私模式")
            ],
            appCategory: .lifestyle
        )
    ],
    dependencies: [
        .package(url: "https://github.com/malcommac/SwiftDate.git", "6.3.1"..<"7.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "SwiftDate", package: "SwiftDate")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
